config/routes.rb
Pincool::Application.routes.draw do
  devise_for :users

  root to: 'static_pages#signup'
  get "/upyun_redirect", to: 'static_pages#upyun_redirect'

  resources :users, only: [:show] do
    member do
      get "followings"
      get "found_brands"
      get "pub_posts"
      get "pub_posts_data"
      get "messages"
      get "messages_data"
      post "messages_readall"
    end
  end

  match "/home", to: "users#home"
  match "/follow_posts_data", to: "users#follow_posts_data",
  as: "follow_posts_data"

  resources :brands do
    member do
      post "follow_toggle"
      get "posts_data"
    end
    resources :posts, except: [:index] do
      resources :comments, only: [:create, :destroy]
    end
  end
  get "explore", to: "posts#index"
  get "explore_data", to: "posts#index_data"

  resources :invited_users, only: [:new, :create, :index, :destroy]

  resources :categories do
    collection do
      get "index_for_admin"
    end
  end

  resources :eva_names, only: [:new, :create, :index, :destroy]

end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  validates_presence_of :email
  validates_presence_of :encrypted_password

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String
  include Mongoid::Timestamps
  field :admin, type: Boolean, default: false
  field :image_url, type: String, default: ""
  field :image_big_url, type: String, default: ""
  field :name, type: String, default: ""

  has_many :found_brands, class_name: 'Brand', inverse_of: :founder
  has_and_belongs_to_many :followings, class_name: 'Brand'
  has_many :posts, inverse_of: :author, validate: false
  embeds_many :messages

  def follow(brand)
    followings.find(brand.id) && return
    followings << brand
    brand.followers << self
  end

  def unfollow(brand)
    followings.delete brand
    brand.followers.delete self
  end

  def follow_posts
    Post.any_in(brand_id: following_ids)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_filter :authenticate_user!

  def home
    if current_user.followings.blank? || params[:recommend]
      @categories = Category.limit(10)
      render 'recommends'
    end
  end

  def follow_posts_data
    @posts = current_user.follow_posts.by_type(params[:type]).page(params[:page])
    render 'shared/posts', layout: false
  end

  def show
    @user = User.find(params[:id])
  end

  def followings
    @user = User.find(params[:id])
    @brands = @user.followings
    render layout: false
  end

  def found_brands
    @user = User.find(params[:id])
    @brands = @user.found_brands
    render "followings", layout: false
  end

  def pub_posts
    @user = User.find(params[:id])
    render layout: false
  end

  def pub_posts_data
    @user = User.find(params[:id])
    @posts = @user.posts.by_type(params[:type]).page(params[:page])
    render 'shared/posts', layout: false
  end

  def messages
    @user = current_user
  end

  def messages_data
    @messages = current_user.messages
    @messages = @messages.unreads if params[:unread]
    render layout: false
  end

  def messages_readall
    Message.readall(current_user)
    redirect_to messages_user_path(current_user)
  end
end

app/helpers/users_helper.rb
# -*- coding: utf-8 -*-
module UsersHelper
  def message_senders(message)
    links = message.senders.map do |sender|
      link_to sender.name, user_path(sender)
    end.take(5).join(',')
    if message.senders.count > 5
      links += "等#{message.senders.count}人"
    end
    raw links
  end
end

app/views/users/_message.html.haml
%li
  = link_to logo_tag(message.brand, :small), brand_path(message.brand)
  %p.message{"data-url" => brand_post_path(message.brand, message.post)}
    = render "message_#{message.type}", message: message
    = time_ago_tag message.created_at

app/views/users/_message_comment.html.haml
= message_senders message
回复了我发在
= link_to message.brand.title, brand_path(message.brand)
- if message.post.author == current_user
  = post_desc message.post
- else
  的回复

app/views/users/followings.html.haml
= render 'brands/brands', brands: @brands

app/views/users/home.html.haml
- provide :title, "我感兴趣的"
%section
  = render "posts/posts", posts_name: "我感兴趣的", posts_url: follow_posts_data_path
- content_for :script do
  :javascript
    $(Pincool.home);

app/views/users/messages.html.haml
- provide :title, @user.name+"的通知"
%section
  %header.messages_head
    %h1= "通知"
    %nav
      = link_to "未读通知(#{@user.messages.unreads.count})", 
      messages_data_user_path(@user, unread: true), remote: true
      = link_to "所有通知(#{@user.messages.count})", 
      messages_data_user_path(@user), remote: true
    = form_tag messages_readall_user_path(@user) do
      = button_tag "我知道了", disable_with: "提交中.."
  %section.messages_content
- content_for :script do
  :javascript
    $(Pincool.userMessages);

app/views/users/messages_data.html.haml
%ul.messages
  = render partial: 'message', collection: @messages

app/views/users/pub_posts.html.haml
%section
  = render "posts/posts", posts_name: "我发布的", posts_url: pub_posts_data_user_path(@user)
:javascript
  $(function(){Pincool.Articles.init()});

app/views/users/recommends.html.haml
- provide :title, '推荐订阅'
%section
  %header
    %h1 推荐订阅
  %section#recommends
    %ul.categories_list
      - @categories.each do |category|
        %li
          .category
            %h2= link_to category.name, category
            %p= link_to category_brands_tag(category), category
          %ul.brands_normal
            = render category.brands.limit(5)

app/views/users/show.html.haml
- provide :title, @user.name
%section
  %header.person_head
    = image_tag @user.image_big_url, class: "people_thumb_big",
      alt: current_user.name
    %h1= @user.name
    %nav
      = link_to "订阅了#{@user.followings.count}个品牌",
      followings_user_path(@user), remote: true
      = link_to "创建了#{@user.found_brands.count}个品牌",
      found_brands_user_path(@user), remote: true
      = link_to "发布了#{@user.posts.count}个帖子",
      pub_posts_user_path(@user), remote: true
  %section.person_content
  - content_for :script do
    :javascript
      $(Pincool.userShow);