config/routes.rb
Pincool::Application.routes.draw do
  devise_for :users

  root to: 'static_pages#signup'
  get "/upyun_redirect", to: 'static_pages#upyun_redirect'

  resources :users, only: [:show] do
    member do
      get "followings"
      get "found_brands"
      get "pub_posts"
      get "pub_posts_data"
      get "messages"
      get "messages_data"
      post "messages_readall"
    end
  end

  match "/home", to: "users#home"
  match "/follow_posts_data", to: "users#follow_posts_data",
  as: "follow_posts_data"

  resources :brands do
    member do
      post "follow_toggle"
      get "posts_data"
    end
    resources :posts, except: [:index] do
      resources :comments, only: [:create, :destroy]
    end
  end
  get "explore", to: "posts#index"
  get "explore_data", to: "posts#index_data"

  resources :invited_users, only: [:new, :create, :index, :destroy]

  resources :categories do
    collection do
      get "index_for_admin"
    end
  end

  resources :eva_names, only: [:new, :create, :index, :destroy]

end

app/models/brand.rb
# -*- coding: utf-8 -*-
class Brand
  include Mongoid::Document
  include Mongoid::Timestamps
  field :title, type: String
  field :uri, type: String
  field :logo, type: String
  field :description, type: String
  field :total_evas, type: Array, default: [0, 0, 0]
  field :eva_names, type: Array, default: %w{设计 性能 实惠}

  belongs_to :founder, class_name: 'User', inverse_of: :found_brands
  has_and_belongs_to_many :followers, class_name: 'User'
  has_many :posts, validate: false
  has_and_belongs_to_many :categories

  validates_presence_of :founder
  validates_presence_of :title, message: "品牌名称不能为空"
  validates_length_of :title, within: 1..20, too_long: "名称最多只能输入%{count}个字"
  validates_presence_of :uri, message: "域名不能为空"
  validates_format_of :uri, with: /^[0-9a-z-]+$/, message: "域名仅限小写字母、数字与“-”"
  validates_length_of :uri, within: 3..255, message: '域名长度应在3-255个字符之间'
  validates_uniqueness_of :uri, case_sensitive: false, message: "此域名已被使用"
  validates_presence_of :logo, message: "请上传logo图片"
  validates_format_of :logo, with: /^\/[0-9a-z]+\.[a-z]+$/
  validates_presence_of :description, message: "一句话简介不能为空"
  validates_length_of :description, within: 1..140, too_long: "简介最多只能输入%{count}个字"

  after_create :followed_by_founder

  paginates_per 20

  default_scope desc(:created_at)

  class << self
    def find_by_uri(uri)
      where(uri: uri).first
    end
  end

  def editable_by?(edit_user)
    edit_user.admin? || founder == edit_user 
  end

  def followed_by?(user)
    followers.find(user.id)
  end

  def followed_by_founder
    founder.follow self
  end

  def reviews
    posts.by_type("review")
  end

  def feelings
    posts.by_type("feeling")
  end

  def evas
    rc = reviews.where(evaluated: true).count
    return [0, 0, 0] if rc <= 0 
    total_evas.map {|eva| eva/rc}
  end

  def update_total_evas(evas)
    evas.each_index do |index|
      total_evas[index] += evas[index]
    end
    save
  end

  def to_param
    uri
  end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create, :show, :posts_data]
  before_filter :author, only: [:edit, :update]

  def new
    @brand = Brand.new
  end

  def create
    @brand = Brand.new(params[:brand].merge(founder: current_user))
    @brand.save ? (redirect_to @brand) : (render 'new')
  end

  def edit
  end

  def update
    @brand.update_attributes(params[:brand]) ?
    (redirect_to @brand) :
      (render 'edit')
  end

  def show
    @brand = Brand.find_by_uri params[:id]
  end

  def index
    @brands = Brand.page params[:page]
  end

  def follow_toggle
    @brand = Brand.find_by_uri params[:id]
    if @brand.followed_by? current_user
      current_user.unfollow @brand
      render "_follow_button", layout: false
    else
      current_user.follow @brand
      render "_unfollow_button", layout: false
    end
  end

  def posts_data
    brand = Brand.find_by_uri params[:id]
    @posts = brand.posts.by_type(params[:type]).page(params[:page])
    render 'shared/posts', layout: false
  end

  private

  def author
    @brand = Brand.find_by_uri params[:id]
    redirect_to(root_path) unless @brand && @brand.editable_by?(current_user)
  end
end

app/helpers/brands_helper.rb
# -*- coding: utf-8 -*-
module BrandsHelper
  def logo_tag(brand, thumb)
    image_tag image_url(:logo, brand.logo, thumb),
    alt: brand.title,
    title: brand.title
  end

  def follow_button_tag(brand)
    follow_text, unfollow_text = "订阅", "退订"
    follow_title = "订阅后,可在我的主页上查看此品牌更新"
    unfollow_title = "退订后,我的主页上将不会收到此品牌更新"
    if current_user && brand.followed_by?(current_user)
      button_tag unfollow_text, title: unfollow_title,
      'id' => 'follow_toggle',
      'class' => "unfollow",
      'data-url' => follow_toggle_brand_path(brand),
      'data-toggle-class' => "follow",
      'data-toggle-text' => follow_text,
      'data-toggle-title' => follow_title
    else
      button_tag follow_text, title: follow_title,
      'id' => 'follow_toggle',
      'class' => "follow",
      'data-toggle-class' => "unfollow",
      'data-url' => follow_toggle_brand_path(brand),
      'data-toggle-text' => unfollow_text,
      'data-toggle-title' => unfollow_title
    end
  end

  def categories_for_select
    Category.all.map {|c| [c.name, c.id]}
  end

  def eva_names_for_select(type)
    EvaName.where(type: type.to_sym).map {|e| e.name}
  end
end

app/views/brands/_brand.html.haml
%li.brand
  = link_to logo_tag(brand, :small), brand_path(brand), class: 'brand_logo'  
  = link_to brand.title.truncate(10), brand_path(brand), class: 'brand_title'
  %p= brand.description.truncate(10)
  = render 'shared/evas', evas: brand.evas, eva_names: brand.eva_names

app/views/brands/_brands.html.haml
%ul.brands_list= render brands

app/views/brands/_fields.html.haml
.field
  = f.text_field :title, placeholder: "请输入品牌名称", size: 20
.field
  %span.prefix= brands_url + '/'
  = f.text_field :uri, placeholder:"请输入品牌域名", size: 20
.field
  = label_tag :file, "请上传品牌logo图片:"
  = upyun_file_field_tag 'file', :logo
  = f.hidden_field :logo
  #dropzone
    - if @brand.logo 
      = logo_tag @brand, :big
      %p 您可以上传替换图片
    - else    
      %p 请上传大小不超过2M的图片
.field
  = f.text_field :description, placeholder: "请填写品牌一句话简介", size: 40
.field
  = f.select "category_ids", categories_for_select, {}, multiple: true, "data-placeholder" => "请选择品牌领域"
.field.eva_names_select
  = label_tag :eva_names, "请选择品牌评测项名称"
- [:r, :b, :g].each_with_index do |type, index|
  .field{"class"=>["eva_names_select", "eva_names_select_#{type}"]}
    %select{name: "brand[eva_names][]"}
      - eva_names_for_select(type).each do |name|
        %option{value: name, selected: @brand.eva_names[index]==name}= name

app/views/brands/_follow_button.html.haml
= button_tag "订阅", title: "订阅后,可在我的主页上查看此品牌更新", class:  "follow", disable_with: "提交中.."

app/views/brands/_follow_form.html.haml
= form_tag follow_toggle_brand_path(@brand), remote: true, 
  id: "follow_toggle", 'data-type' => 'html' do
  - if current_user && @brand.followed_by?(current_user)
    = render "unfollow_button"
  - else
    = render "follow_button"

app/views/brands/_unfollow_button.html.haml
= button_tag "已订阅 | 取消", title: "取消后,我的主页上将不会收到此品牌更新", class:  "unfollow", disable_with: "提交中.."

app/views/brands/edit.html.haml
- provide :title, "编辑-#{@brand.title}"
%section
  %header
    %h1= yield :title
  %section.brand_form
    = form_for @brand, validate: true do |f| 
      = render 'fields', f: f
      .action  
        = f.button "保存"
        = f.button "取消", type: "cancel"
- content_for :script do
  :javascript
    $(Pincool.brandForm);

app/views/brands/index.html.haml
%section
  %header
    %h1 新增品牌列表(管理)
  %table
    %tr
      %th= "品牌名称"
      %th= "品牌网址"
      %th= "Logo"
      %th= "创建用户"
    - @brands.each do |brand|  
      %tr
        %td= brand.title
        %td= link_to brand_url(brand), brand_path(brand)
        %td= logo_tag brand, :small 
        %td= link_to brand.founder.name, user_url(brand.founder)
  = paginate @brands

app/views/brands/new.html.haml
- provide :title, "建立新品牌"
%section
  %header
    %h1= yield :title
  %section.brand_form
    = form_for @brand, validate: true do |f| 
      = render 'fields', f: f
      .action  
        = f.button "发布"
        = f.button "取消", type: "cancel"
- content_for :script do
  :javascript
    $(Pincool.brandForm);

app/views/brands/show.html.haml
- provide :title, raw(@brand.title)
%section
  %header#brand_head
    #title
      = logo_tag @brand, :big
      = render "follow_form"
      %p
        %span#followers_count= @brand.followers.count
        人已订阅
    #info
      %h1= @brand.title
      %p= @brand.description
      - if current_user && @brand.editable_by?(current_user)
        %p= link_to "[编辑]", edit_brand_path(@brand)
      = render 'shared/evas', evas: @brand.evas, eva_names: @brand.eva_names      
    #tags
      %h2 领域
      %ul
        - @brand.categories.each do |category|
          %li= link_to category.name, category
  %section#brand_publish
    = link_to "品牌感受", new_brand_post_path(@brand)+"?type=feeling", "class" => "feeling_pub"
    = link_to "产品评价", new_brand_post_path(@brand)+"?type=review", "class" => "review_pub"
  = render "posts/posts", posts_name: @brand.title+"的帖子", posts_url: posts_data_brand_path(@brand)
- content_for :script do
  :javascript
    $(Pincool.brandShow);