config/routes.rb
Pincool::Application.routes.draw do
  devise_for :users

  root to: 'static_pages#signup'
  get "/upyun_redirect", to: 'static_pages#upyun_redirect'

  resources :users, only: [:show] do
    member do
      get "followings"
      get "found_brands"
      get "pub_posts"
      get "pub_posts_data"
      get "messages"
      get "messages_data"
      post "messages_readall"
    end
  end

  match "/home", to: "users#home"
  match "/follow_posts_data", to: "users#follow_posts_data",
  as: "follow_posts_data"

  resources :brands do
    member do
      post "follow_toggle"
      get "posts_data"
    end
    resources :posts, except: [:index] do
      resources :comments, only: [:create, :destroy]
    end
  end
  get "explore", to: "posts#index"
  get "explore_data", to: "posts#index_data"

  resources :invited_users, only: [:new, :create, :index, :destroy]

  resources :categories do
    collection do
      get "index_for_admin"
    end
  end

  resources :eva_names, only: [:new, :create, :index, :destroy]

end

app/views/layouts/_footer.html.haml
%footer

app/views/layouts/_header.html.haml
%header
  %nav
    #logo
      = link_to(root_path) do
        = image_tag "logo.png", title: "返回主页", alt: "logo"
    %ul#navigator
      %li= link_to "我的主页", root_path
      %li= link_to "我的品牌", user_path(current_user)
      %li= link_to "探索发现", explore_path
      %li= link_to "品控领域", categories_path
    #messages_tip
      - messages_count = current_user.messages.unreads.count
      = link_to messages_count,
      messages_user_path(current_user),
      title: "我有#{messages_count}个未读通知",
      "class" => (messages_count > 0)?"":"no_messages"
    #current_user
      = link_to current_user do
        = image_tag current_user.image_url, class: "people_thumb_small",
        title: current_user.name, alt: current_user.name
        %strong= current_user.name.truncate(9)
      %ul
        %li= link_to "建立新品牌", new_brand_path
        - if current_user.admin?
          %li= link_to "*邀请用户管理", invited_users_path
          %li= link_to "*品牌管理", brands_path
          %li= link_to "*领域管理", index_for_admin_categories_path
          %li= link_to "*评测项管理", eva_names_path
        %li= link_to "退出", destroy_user_session_path, method: :delete

app/views/layouts/application.html.haml
!!!
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="zh-CN"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="zh-CN"> <!--<![endif]-->
%head
  %meta(charset="utf-8")
  %meta(name="author" content="lilu.life@gmail.com")
  %meta(name="description" content="品酷-不一样的在线品牌点评服务")
  %meta(name="viewport" content="width=device-width,initial-scale=1")
  %meta(property="wb:webmaster" content="7b4481bdd397f2e0")
  %title= full_title yield(:title)
  = stylesheet_link_tag "application"
  = javascript_include_tag "application"
  = csrf_meta_tags
%body{id: params[:controller], class: ((signed_in?) ? "signed_in" : "sign_up")}
  - if signed_in?
    = render 'layouts/header'
    = yield
    = render 'layouts/footer'
  - else
    = yield
  = yield :script
  = javascript_include_tag "ga"
  -# = javascript_include_tag "proto_fluid.3.02" if Rails.env.development?
  -# = debug(params) if Rails.env.development?
</html>